/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphic;

import biweekly.component.VEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Set;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import maxcal.Data;
import static maxcal.Manipulation.convertListToMap;
import static maxcal.Manipulation.getDates;

/**
 *
 * @author maxime
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        buttonGroup1.add(radioButG1);
        buttonGroup1.add(radioButG2);
        buttonGroup1.add(radioButGAll);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonBrowseFile = new javax.swing.JButton();
        labelConfirmPath = new javax.swing.JLabel();
        buttonLoad = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        radioButG1 = new javax.swing.JRadioButton();
        radioButG2 = new javax.swing.JRadioButton();
        radioButGAll = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MaxCal 2016");
        setPreferredSize(new java.awt.Dimension(800, 600));

        buttonBrowseFile.setText("Browse file");
        buttonBrowseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBrowseFileActionPerformed(evt);
            }
        });

        labelConfirmPath.setText("No file chosen");

        buttonLoad.setText("Load");
        buttonLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoadActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Date", "Début", "Fin", "TitreCours", "Lieu", "OpenFiles"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(150);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(150);
            jTable1.getColumnModel().getColumn(1).setMinWidth(60);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(60);
            jTable1.getColumnModel().getColumn(2).setMinWidth(60);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(60);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(100);
        }

        radioButG1.setText("Groupe1");
        radioButG1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButG1ActionPerformed(evt);
            }
        });

        radioButG2.setText("Groupe2");
        radioButG2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButG2ActionPerformed(evt);
            }
        });

        radioButGAll.setText("Tous");
        radioButGAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButGAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioButG1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioButG2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioButGAll)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonBrowseFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelConfirmPath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonLoad))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBrowseFile)
                    .addComponent(labelConfirmPath)
                    .addComponent(buttonLoad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButG1)
                    .addComponent(radioButG2)
                    .addComponent(radioButGAll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBrowseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBrowseFileActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser("ics");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("ICalendar format", "ics");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            labelConfirmPath.setText(chooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_buttonBrowseFileActionPerformed

    private void buttonLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoadActionPerformed
        // TODO add your handling code here:
        String path = labelConfirmPath.getText();
        // Init 
        Data.initData();
        Data.initListEvents(path);
        setTableWithEvents(Data.listEvents);
    }//GEN-LAST:event_buttonLoadActionPerformed

   

    private int computeSizeWithMap(HashMap<String, ArrayList<VEvent>> map) {
        Set set = map.keySet();
        Iterator it = set.iterator();
        int nb = 0;
        while (it.hasNext()) {
            nb++;
            String cle = (String) it.next();
            ArrayList<VEvent> listeTmp = map.get(cle);
            nb += listeTmp.size();
        }
        return nb;
    }
    
    private void setTableWithEvents(ArrayList<VEvent> listEvents) {
        SimpleDateFormat ft = new SimpleDateFormat("'Le' dd.MM.yyyy");
        SimpleDateFormat ft2 = new SimpleDateFormat("HH:mm");

        ArrayList<String> listDates = getDates(listEvents);
        HashMap<String, ArrayList<VEvent>> map = convertListToMap(listEvents);
        
        Object[][] obj = new Object[computeSizeWithMap(map)][6];
        int i = 0;
        
        for(String date : listDates) {
            obj[i][0] = "Le " + date;
            i++;
            ArrayList<VEvent> listeTmp = map.get(date);
            for (VEvent event : listeTmp) {
                obj[i][1] = ft2.format(event.getDateStart().getValue());
                obj[i][2] = ft2.format(event.getDateEnd().getValue());
                obj[i][3] = event.getSummary().getValue();
                String str = event.getLocation().getValue().replaceAll("Manufacture", "PLG");
                String str2 = str.replaceAll("_", " - ");
                obj[i][4] = str2;
                obj[i][5] = null;
                i++;
            }
        }

        // Set Table
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                obj,
                new String[]{
                    "Date", "Début", "Fin", "TitreCours", "Lieu", "OpenFiles"
                }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(150);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(150);
            jTable1.getColumnModel().getColumn(1).setMinWidth(60);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(60);
            jTable1.getColumnModel().getColumn(2).setMinWidth(60);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(60);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(100);
        }
    }
    private void radioButG2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButG2ActionPerformed
        // TODO add your handling code here:
        ArrayList<VEvent> eventsG2 = new ArrayList<>();
        for (VEvent event : Data.listEvents) {
            if (event.getSummary().getValue().startsWith("CM") || !event.getSummary().getValue().contains("G1")) {
                eventsG2.add(event);
            }
        }
        setTableWithEvents(eventsG2);
    }//GEN-LAST:event_radioButG2ActionPerformed

    private void radioButG1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButG1ActionPerformed
        // TODO add your handling code here:
        ArrayList<VEvent> eventsG1 = new ArrayList<>();
        for (VEvent event : Data.listEvents) {
            if (event.getSummary().getValue().startsWith("CM") || !event.getSummary().getValue().contains("G2")) {
                eventsG1.add(event);
            }
        }
        setTableWithEvents(eventsG1);
    }//GEN-LAST:event_radioButG1ActionPerformed

    private void radioButGAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButGAllActionPerformed
        // TODO add your handling code here:
        setTableWithEvents(Data.listEvents);
    }//GEN-LAST:event_radioButGAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBrowseFile;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonLoad;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelConfirmPath;
    private javax.swing.JRadioButton radioButG1;
    private javax.swing.JRadioButton radioButG2;
    private javax.swing.JRadioButton radioButGAll;
    // End of variables declaration//GEN-END:variables
}
